Return GraphQL JSON response in case of JSON Input error instead of Internal Server Error
thecodingmachine/graphqlite-bundle pull request #208
Opened 2024-04-17 17:38 UTC by cvergne

Fixes #207 

---

The purpose of the PR is to return a standard GraphQL JSON error response in case of JSON error in given input (request body).

It adds an Exception Listener which set a JsonResponse in case of thrown GraphQLExceptionInterface (to catch any GraphQL Exception outside of the GraphQL Server context).

Also added the two exception cases of the controller into errors functional tests.

> [!NOTE]
> Got an error when running test about `DependencyInjection/Configuration.php` not compatible with implemented interface, so fixed it but tell me if I should remove it and fixed in another PR.

2024-05-05 00:21 UTC, homersimpsons commented
I will let @mistraloz review this as you discussed it.

About the implementation I'm okay with the current status. But I'm feeling that it may be too complex, this adds a lew listener, a new exception (which names conflict with a std one).

I think this is the right way to approach this as the end user will have enough control on it. But maybe a simple `return new JsonResponse(..., 422)` would have been sufficient.

Thank you for the tests too!

2024-11-07 02:59 UTC, cvergne commented
May we reopen this pull request as it just needs review ? :)

2025-01-01 20:11 UTC, andrew-demb commented
@cvergne what do you think about such refactoring - to avoid introducing an exception listener for now (as suggested in https://github.com/thecodingmachine/graphqlite-bundle/pull/208#issuecomment-2094515479)?

https://github.com/andrew-demb/graphqlite-bundle/commit/cf664c3a3ac3e64ef10b4fc36d87685a882e8212

2025-01-03 19:57 UTC, Lappihuan commented
@andrew-demb looks good, we ended up adding a listener in our app to make sure we always return a valid json in `/graphql` but it always felt hacky.

2025-01-03 20:21 UTC, andrew-demb commented
@cvergne please rebase this PR over the current master with the applied suggestion from https://github.com/thecodingmachine/graphqlite-bundle/pull/208#issuecomment-2567131820

2025-01-03 22:00 UTC, cvergne commented
@andrew-demb I will do it by tuesday at the latest 😉

2025-01-05 22:08 UTC, andrew-demb approved these changes

2025-01-05 22:25 UTC, cvergne commented
@andrew-demb Please do not merge it yet, I have to check why the tests are failing. I'll do it this monday 😉

2025-01-05 22:28 UTC, andrew-demb requested changes

2025-01-05 22:28 UTC, andrew-demb commented on Exceptions/JsonException.php
should be moved to `src/Exceptions`

2025-01-06 15:47 UTC, cvergne commented
Alright, all green about tests.
_I didn't even noticed some of my files were not in src… 🤦_

2025-01-06 15:55 UTC, andrew-demb approved these changes

2025-01-06 19:16 UTC, merged

2025-01-06 19:18 UTC, andrew-demb commented
Thank you @cvergne 

Released in v7.1.0 https://github.com/thecodingmachine/graphqlite-bundle/releases/tag/v7.1.0